//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BodyBasicIndex
    {
        public string ID { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string BMI { get; set; }
        public string BodyFat { get; set; }
        public string SkeletalMuscleRate { get; set; }
        public string VisceralFat { get; set; }
        public System.DateTime Date { get; set; }
    }
}
