//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkoutWeb.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WorkoutEntities1 : DbContext
    {
        public WorkoutEntities1()
            : base("name=WorkoutEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BodyBasicIndex> BodyBasicIndex { get; set; }
        public virtual DbSet<CalorieRecord> CalorieRecord { get; set; }
        public virtual DbSet<Food> Food { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<WorkoutItem> WorkoutItem { get; set; }
        public virtual DbSet<WorkoutOrder> WorkoutOrder { get; set; }
        public virtual DbSet<WorkoutRecordDetail> WorkoutRecordDetail { get; set; }
        public virtual DbSet<WrokoutRecord> WrokoutRecord { get; set; }
    }
}
